### ISSUE TITLE
Child app change page

### ISSUE THREAD

**Issue by MatheoPons** [cincheo/daquota#103]
The user should be able to change page in a child app with an event.

The user have a button in a child app and want to go to another tab in the parent nav bar when the button is clicked.

**Comment by renaudpawlak** [comment]
Todo: use ``$tools.go(pageId)``... if ``pageId`` does not exist in child, it will ask the parent to go to the given ``pageId``.

**Comment by renaudpawlak** [comment]
Now one can use ``$tools.go(pageId, true)`` to navigate in the top-level window, when embedded in a parent dLite app.
