### ISSUE TITLE
heelp needed: a very simple books table. But i can not get my books added

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#13]
hello Renaud,

I tried to learn form the examples but Dlite still has some mysteries.
I can not get my add-button to add books to this simple books-table. What am i missing?
I added a copy of the books.dlite file. By the ay: i need to change the file name by adding a.txt extension. Otherwise the dlite file can not be added to this issue

BTW 
kind regards
Folkert
[books.dlite.txt](https://github.com/cincheo/dlite/files/8728770/books.dlite.txt)

**Comment by renaudpawlak** [comment]
Did you find a way?
Instead of uploading a dlite file, you can also cut and paste your main container in the issue. It will paste it as JSON and I can paste it back in my project to test it.
