### ISSUE TITLE
"My projects" and "example projects"  in the Dlite platform have disappeared since today. 

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#153]
Hi Renaud

Is this on purpose?

Regards
Folkert

**Comment by renaudpawlak** [comment]
It was a bug but it should be fixed hopefully. Could you try again and confirm the fix ?

**Comment by renaudpawlak** [comment]
Examples should be back too - they were broken also :(

**Comment by HFolkertH** [comment]
examples are there. But my projects not.

**Comment by renaudpawlak** [comment]
That's probably because of your Browser's cache. I need to look closer.

**Comment by renaudpawlak** [comment]
Ok. Could you please try again, first making sur that you clear all your browser cache (cache sites data)? 
If possible, it would be better if you can also clear the IndexedDB of platform.dlite.io, but not mandatory I think.
You can also try with a new browser / session. 
The projects may take some time to appear. 
It is hard to debug without having the developper tools. If the problem persist, we might have to have a visio.

**Comment by HFolkertH** [comment]
Thanx!. My project are back again!

**Comment by renaudpawlak** [comment]
Great. Let's cross finger this bug is solved for good...
