### ISSUE TITLE
storage manager does not show my local storage objects anymore

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#154]
hi Renaud,

It was possible to see and edit my own objects in my local storages. But not anymore. I only see the Dlite system objects.

![image](https://user-images.githubusercontent.com/22573455/230607288-293ea26d-9b61-4dad-899c-de324e9a541f.png)
 
Folkert

**Comment by renaudpawlak** [comment]
True. I switched from Local Storage to IndexedDB, but I did not update the storage manager yet... I will ASAP (very busy)

**Comment by HFolkertH** [comment]
Hi Renaud,

The storage management now shows a lot of stores. A lot are system stores, some belong to you and some belong to me.
But my newest store on IndexDB is not shown.

![image](https://user-images.githubusercontent.com/22573455/231165934-7c8c851e-1cf9-4fb5-84bd-bedcccb20855.png)

**Comment by renaudpawlak** [comment]
The storage tool should work again with the new version. Note that it is not local storage based, but for IndexedDB now (dLite database).
