### ISSUE TITLE
Allow CID renaming

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/daquota#40]
Renaming of components should be allowed for readability purpose.

**Comment by HFolkertH** [comment]
using/printing  the Anchor name directly after a CID in a model could also be sufficient

**Comment by renaudpawlak** [comment]
Well, I have thought of it too, but anchors are made for locating and referencing DOM elements in the HTML page. So, I prefer having these two references systems quite independent and keep for their own uses. I'll see how it goes when I'll dive in the implementation detail.

**Comment by renaudpawlak** [comment]
Components can be renamed now, so I have moved the anchor property to the "..." section (to avoid confusion, since it should not be used as a public name)
