### ISSUE TITLE
New json form on dlite.io does not open in the IDE

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#52]
Hi Renaud,

On the new dlite.io website i tried to copy the generated Json to a project with the “click here”. But it does not work. The ide opens with an empty project. I am on macos big sur with the newest Chrome.

**Comment by renaudpawlak** [comment]
The generated form should not appear directly in the projet, but now, a help popover should open and invite you to paste it (and under Chrome it should work if you allow pasting). Shall I close this issue? Please don't hesitate to tell me if something is still bothering you. I might be missing something, or there might be some bug(s) left.

**Comment by HFolkertH** [comment]
hi Renaud,

Im am using Chrome. But clicking on click here leads me to an empty project in the Ide.
![image](https://user-images.githubusercontent.com/22573455/185140868-b36f781d-aae7-41c2-9e3e-73f19b8b7298.png)

If I go to generic builder and paste the clipboard then I get the Form-Json there, but not the generated input fields structure.
Where exactly should I paste the generated form specs?

1 other thing: on this demo webpage it says "project" instead of "project".
![image](https://user-images.githubusercontent.com/22573455/185140382-f7d14e23-be81-4b43-aa3f-ae931b720d5a.png)

**Comment by renaudpawlak** [comment]
But you don't need to go to the generic builder. If you paste "as is", it will generate the form in the "index" container. You can also create and select another container before pasting. The point with the work I have done on copy-paste is that you don't need to use generic builders anymore. It's all automatic and transparent.

**Comment by renaudpawlak** [comment]
I might add a useClipboard option... That would be nice...

**Comment by renaudpawlak** [comment]
I have added a way to encode an app or a component in a URL :) So it works not !
