### ISSUE TITLE
Input component label gone?

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#53]
If i start a new blanco project and add an input-component, then i can not add a label to that input anymore.
Older project stilll have the label attribute, but new/blanco projects don’t.

**Comment by renaudpawlak** [comment]
Ouch... really? I don't see that bug. Do you have a screenshot? Maybe try to clear you browser cache?

**Comment by renaudpawlak** [comment]
Can you open the developper mode and see if there are errors in the console? (command+option+i on most browsers)

**Comment by renaudpawlak** [comment]
Can we close this issue? If there is still a problem, can you send me the JSON code of the faulty component please?

**Comment by renaudpawlak** [comment]
Unable to reproduce.
