### ISSUE TITLE
Very unhandy to pick a year in Datepicker

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#54]
Hi Remaud

it takes ages to select my birthday (1963) in the standard datepicker, like in the contact demo. Could the year in the Datepicker be selected and open a listbox with yearnumbers?

**Comment by renaudpawlak** [comment]
I have added a switch to enable per-decade navigation. It should be available in the next release (coming tomorrow if everything goes as expected). Myself being born in 1973, I will certainly find it useful ;)

**Comment by HFolkertH** [comment]
My first IT was with punch cards. So what am i complaining about 🤓

**Comment by renaudpawlak** [comment]
Should be deployed now.

**Comment by HFolkertH** [comment]
Nice!
