### ISSUE TITLE
Iterator page gives a 404

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#62]
Hello Renauld,

I was looking for an example to sum some values in an iterator. Checking the iterator help ( https://github.com/cincheo/dlite/blob/main/src/components/iterator-view.js ) page gives a 404/not found.

Kind regards 
Folkert

**Comment by renaudpawlak** [comment]
Fixed... but it only give access to the source code.
Not sure that the iterator is the right place to look at. Normally, if you want to sum some values in an array data you just need to use a function.
