### ISSUE TITLE
Unable to use function on background and border color of a chart when there is series

### ISSUE THREAD

**Issue by MatheoPons** [cincheo/daquota#75]
### Unable to use function on background and border color of a chart

**SITUATION**
I'm using a chart that have series, and want to make the color of the background and the border a function.

**PROBLEM**
The function button doesn't exist for these parameters.

**Comment by renaudpawlak** [comment]
Please do not use series if you need to have dynamic colors. Normally you can do all customizations without series. If not, please report.
