### ISSUE TITLE
model editor complains about screen size

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#9]
![image](https://user-images.githubusercontent.com/22573455/168642018-bcf24f87-dcec-4737-bd60-1350a64dc5fe.png)

Apple will not like you. The screen of my Macbook Air is too small to open de model editor. A bug or on purpose?

**Comment by renaudpawlak** [comment]
OOps. I might have been a little too restrictive on the size constraint. This part is not responsive and I added a silly condition on the size. I will remove it asap.

**Comment by renaudpawlak** [comment]
I have released version 0.9.5, which removes the screen width limitation. You can checked how it was done in the models.dlite app (fairly easy). The model is now usable with screens smaller than 768px, but you'll have to scroll horizontally to see all the info. Hope you will manage to use the model editor. It will be improved in the future ;)

**Comment by HFolkertH** [comment]
Working now. Thanks!
